### ISSUE TITLE
Failed to load the google-closure package

### ISSUE THREAD

**Issue by william-index** [grobertson/atom-google-closure#3]
[Enter steps to reproduce below:]

1.Start atom while closure package is installed.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.4
**Thrown From**: [google-closure](https://github.com/grobertson/atom-google-closure) package, v0.1.0
### Stack Trace

Failed to load the google-closure package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/.atom/packages/google-closure/lib/atom-google-closure-view.coffee:4:199)
    at /.atom/packages/google-closure/lib/atom-google-closure-view.coffee:9:5
    at Object.<anonymous> (/.atom/packages/google-closure/lib/atom-google-closure-view.coffee:52:5)
    at Object.<anonymous> (/.atom/packages/google-closure/lib/atom-google-closure-view.coffee:54:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "Atomic-TWA"
    ],
    "disabledPackages": [
      "atom-jade",
      "minimap-color-highlight"
    ],
    "ignoredNames": [
      ".DS_Store"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
Atomic-TWA, v0.9.0
autocomplete-python, v0.5.3
google-closure, v0.1.0
language-65asm, v2.0.0
language-gherkin, v1.0.2
language-jade, v0.6.2
language-python-django-templates, v0.1.0
language-soy, v0.2.0
linter-gjslint, v0.0.5
linter-python-pep8, v0.2.0
linter-tidy, v1.0.1
python-isort, v0.0.7

# Dev
No dev packages
```

**Comment by rachlenko** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [google-closure](https://github.com/grobertson/atom-google-closure) package, v0.1.0

### Stack Trace

Failed to load the google-closure package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/erachlenko/.atom/packages/google-closure/lib/atom-google-closure-view.coffee:1:1)
    at /Users/erachlenko/.atom/packages/google-closure/lib/atom-google-closure-view.coffee:5:3
    at Object.<anonymous> (/Users/erachlenko/.atom/packages/google-closure/lib/atom-google-closure-view.coffee:5:3)
    at Object.<anonymous> (/Users/erachlenko/.atom/packages/google-closure/lib/atom-google-closure-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/erachlenko/.atom/packages/google-closure/lib/atom-google-closure.coffee:1:25)
    at Object.<anonymous> (/Users/erachlenko/.atom/packages/google-closure/lib/atom-google-closure.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
angularjs, v0.3.4
autocomplete-awk, v0.1.2
autocomplete-clang, v0.8.9
autocomplete-elixir, v1.5.12
autocomplete-go, v0.2.0
autocomplete-json, v1.5.0
autocomplete-python, v1.6.1
autocomplete-ruby, v0.1.0
autocomplete-swift, v1.0.1
autocomplete-xml, v0.8.1
build-tools, v4.3.3
environment, v1.1.1
go-config, v0.3.3
go-get, v0.1.1
go-plus, v3.5.2
google-closure, v0.1.0
haskell-grammar, v0.4.0
ide-haskell-cabal, v1.0.0
jira-issue-search, v0.2.2
language-chef, v0.8.0
language-coffee-script-angular, v2.2.0
language-coffeescript-html, v0.48.0
language-cpp14, v0.6.0
language-haskell, v1.5.2
language-swift, v0.4.0
levels-language-ruby, v0.5.0
linter, v1.11.3
linter-checkbashisms, v0.1.5
linter-coffeelint, v1.1.2
linter-golinter, v1.1.0
linter-hlint, v0.4.2
linter-swift-package-manager, v0.1.0
pretty-json, v0.4.1
python-indent, v0.3.2
python-tools, v0.6.7
spell-check-project, v0.4.0
travis-ci-status, v1.0.0
xml-tools, v0.2.1

# Dev
No dev packages
```

Could you help me to fix it ?

**Comment by krrg** [comment]
+1 same issue as @rachlenko

**Comment by moaiii** [comment]
+1 same issue as @krrg

**Comment by BenjaminHCCarr** [comment]
Issues: #1 #2 #3 are all basically the same

Has anyone found the solution? Still having this issue.

**Comment by rachlenko** [comment]
Nope
